development:
  adapter: postgresql
  database: mapbadger

test: &test
  adapter: postgresql
  database: mapbadger_test

production:
  adapter: postgresql
  database: mapbadger

cucumber:
  <<: *test

