development:
  adapter: postgresql
  database: mapbadger

test: &test
  adapter: postgresql
  database: mapbadger_test
  template: template_postgis

production:
  adapter: postgresql
  database: mapbadger

cucumber:
  <<: *test

