development:
  adapter: postgis
  database: mapbadger
  template: template_postgis

test: &test
  adapter: postgis
  database: mapbadger_test
  template: template_postgis

production:
  adapter: postgis
  database: mapbadger

cucumber:
  <<: *test

