default:
  aws_access_key_id: 'AKIAIGOSLFRML62BDFLQ'       # required
  aws_secret_access_key: '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'       # required
  region: 'us-east-1'  # optional, defaults to 'us-east-1'
