--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: mapbadger.com
  external_host: ec2-184-73-81-215.compute-1.amazonaws.com
  external_ip: 184.73.81.215
  image_id: ami-7000f019
  image_type: m1.small
  instance_id: i-3c98c15e
  internal_host: ip-10-110-59-127.ec2.internal
  internal_ip: 10.110.59.127
  name: beta
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: !str:HighLine::String app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  root_device_type: instance-store
  security_groups: 
  - mapbadger_production_default
  - mapbadger_production_beta
  - mapbadger_production_app
  - mapbadger_production_passenger
  - mapbadger_production_apache
  zone: us-east-1b
- volumes: {}

  static_ips: {}

